name       : keepass
version    : '2.36'
release    : 19
source     :
    - https://netcologne.dl.sourceforge.net/project/keepass/KeePass%202.x/2.36/KeePass-2.36-Source.zip : de7e3e9d9bedab13e4d66b0ee941b2ebedaa08d8090f7cd78bd0fc019187d8c8
license    : GPL-2.0
component  : security
summary    : KeePass Password Safe is a free, open source, lightweight, and easy-to-use
    password manager.
description: |
    KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager.
extract    : no
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - pkgconfig(mono-addins)
    - libgdiplus-devel
    - unzip
rundeps    :
    - libgdiplus
    - mono
    - mono-devel
    - mono-addins
    - xdotool
    - xsel
setup      : |
    unzip $sources/KeePass-${version}-Source.zip
    # "Convert" to mono 4.0
    sed -i '1s/ 10.00/ 11.00/' KeePass.sln
    find . -name "*.csproj" -exec sed -i '1s/"3.5"/"4.0"/' {} +
build      : |
    cd ../Build/
    chmod +x PrepMonoDev.sh
    ./PrepMonoDev.sh
    cd ../
    xbuild /target:KeePass /property:Configuration=Release
    cp Ext/KeePass.exe.config Build/KeePass/Release
install    : |
    cd $workdir/../
    install -dm755 $installdir/usr/bin
    install -dm755 $installdir/usr/share/keepass/XSL

    install -Dm755 Build/KeePass/Release/KeePass.exe $installdir/usr/share/keepass/KeePass.exe
    install -Dm755 Ext/KeePass.config.xml $installdir/usr/share/keepass/KeePass.config.xml
    install -Dm755 Ext/KeePass.exe.config $installdir/usr/share/keepass/KeePass.exe.config
    install -m644 Ext/XSL/* $installdir/usr/share/keepass/XSL

    install -Dm644 $pkgfiles/keepass.png $installdir/usr/share/pixmaps/keepass.png

    # KeePass Desktop File and Exec Adding

    echo '#!/bin/sh
    exec mono /usr/share/keepass/KeePass.exe "$@"' >> $installdir/usr/bin/keepass
    chmod +x $installdir/usr/bin/keepass
    install -Dm644 $pkgfiles/keepass.desktop $installdir/usr/share/applications/keepass.desktop
