name       : keepass
version    : 2.32
release    : 9
source     :
    - http://freefr.dl.sourceforge.net/project/keepass/KeePass%202.x/2.32/KeePass-2.32-Source.zip : 7c49b62c8de758dee7e9c2d6108c169d468b4e65f21e297649d3dd8c2b757385
license    : GPL-2.0
summary    : KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager.
description: |
    KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager.
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - pkgconfig(mono-addins)
    - libgdiplus-devel
rundeps :
    - libgdiplus
    - mono
    - mono-devel
    - mono-addins
setup      : |
    # "Convert" to mono 4.0
    sed -i '1s/ 10.00/ 11.00/' KeePass.sln
    find . -name "*.csproj" -exec sed -i '1s/"3.5"/"4.0"/' {} +
    cd Build
    chmod +x PrepMonoDev.sh
    ./PrepMonoDev.sh
    cd ../
build      : |
    xbuild /target:KeePass /property:Configuration=Release
    cp Ext/KeePass.exe.config Build/KeePass/Release
install    : |
    install -dm755 %installroot%/usr/bin
    install -dm755 %installroot%/usr/share/keepass/XSL

    install -Dm755 Build/KeePass/Release/KeePass.exe %installroot%/usr/share/keepass/KeePass.exe
    install -Dm755 Ext/KeePass.config.xml %installroot%/usr/share/keepass/KeePass.config.xml
    install -Dm755 Ext/KeePass.exe.config %installroot%/usr/share/keepass/KeePass.exe.config
    install -m644 Ext/XSL/* %installroot%/usr/share/keepass/XSL

    install -Dm644 KeePass/KeePass.ico %installroot%/usr/share/icons/KeePass.ico

    # KeePass Desktop File and Exec Adding

    echo '#!/bin/sh
    exec mono /usr/share/keepass/KeePass.exe "$@"' >> %installroot%/usr/bin/keepass
    chmod +x %installroot%/usr/bin/keepass
    install -Dm644 $pkgfiles/keepass.desktop $installdir/usr/share/applications/keepass.desktop
