name       : keepass
version    : 2.33
release    : 11
source     :
    - http://freefr.dl.sourceforge.net/project/keepass/KeePass%202.x/2.33/KeePass-2.33-Source.zip : 5120a490289155a8b49c8e6893a2cc4b20fe859b34f815f17a017bae449f9958
license    : GPL-2.0
component  : security
summary    : KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager.
description: |
    KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager.
extract    : no
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - pkgconfig(mono-addins)
    - libgdiplus-devel
    - unzip
rundeps :
    - libgdiplus
    - mono
    - mono-devel
    - mono-addins
setup      : |
    unzip $sources/KeePass-2.33-Source.zip
    # "Convert" to mono 4.0
    sed -i '1s/ 10.00/ 11.00/' KeePass.sln
    find . -name "*.csproj" -exec sed -i '1s/"3.5"/"4.0"/' {} +
build      : |
    cd ../Build/
    chmod +x PrepMonoDev.sh
    ./PrepMonoDev.sh
    cd ../
    xbuild /target:KeePass /property:Configuration=Release
    cp Ext/KeePass.exe.config Build/KeePass/Release
install    : |
    cd $workdir/../
    install -dm755 %installroot%/usr/bin
    install -dm755 %installroot%/usr/share/keepass/XSL

    install -Dm755 Build/KeePass/Release/KeePass.exe %installroot%/usr/share/keepass/KeePass.exe
    install -Dm755 Ext/KeePass.config.xml %installroot%/usr/share/keepass/KeePass.config.xml
    install -Dm755 Ext/KeePass.exe.config %installroot%/usr/share/keepass/KeePass.exe.config
    install -m644 Ext/XSL/* %installroot%/usr/share/keepass/XSL

    install -Dm644 KeePass/KeePass.ico %installroot%/usr/share/icons/KeePass.ico

    # KeePass Desktop File and Exec Adding

    echo '#!/bin/sh
    exec mono /usr/share/keepass/KeePass.exe "$@"' >> %installroot%/usr/bin/keepass
    chmod +x %installroot%/usr/bin/keepass
    install -Dm644 $pkgfiles/keepass.desktop $installdir/usr/share/applications/keepass.desktop
