name       : keepass
version    : '2.47'
release    : 34
source     :
    - https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.47/KeePass-2.47-Source.zip : 8782d6e778481a8a47ebf624cd6043b0c3f90273830a6b67f0090e84bbb762a9
license    : GPL-2.0-or-later
component  : security
summary    : KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager
description: |
    KeePass Password Safe is a free, open source, lightweight, and easy-to-use password manager.
extract    : no
builddeps  :
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(mono)
    - libgdiplus-devel
rundeps    :
    - libgdiplus
    - mono-devel
    - xdotool
    - xsel
setup      : |
    unzip $sources/KeePass-${version}-Source.zip
    # "Convert" to mono 4.0
    sed -i '1s/ 10.00/ 11.00/' KeePass.sln
    find . -name "*.csproj" -exec sed -i '1s/"3.5"/"4.0"/' {} +
build      : |
    cd ../Build/
    chmod +x PrepMonoDev.sh
    ./PrepMonoDev.sh
    cd ../
    xbuild /target:KeePass /property:Configuration=Release
    cp Ext/KeePass.exe.config Build/KeePass/Release
install    : |
    cd $workdir/../
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/usr/share/keepass/XSL

    install -Dm00755 Build/KeePass/Release/KeePass.exe $installdir/usr/share/keepass/KeePass.exe
    install -Dm00755 Ext/KeePass.config.xml $installdir/usr/share/keepass/KeePass.config.xml
    install -Dm00755 Ext/KeePass.exe.config $installdir/usr/share/keepass/KeePass.exe.config
    install -m00644 Ext/XSL/* $installdir/usr/share/keepass/XSL

    install -Dm00644 $pkgfiles/keepass.png $installdir/usr/share/pixmaps/keepass.png

    # KeePass Desktop File and Exec Adding

    echo '#!/bin/sh
    exec mono /usr/share/keepass/KeePass.exe "$@"' >> $installdir/usr/bin/keepass
    chmod +x $installdir/usr/bin/keepass
    install -Dm00644 $pkgfiles/keepass.desktop $installdir/usr/share/applications/keepass.desktop
